formatters:
    dashed:
        class: Monolog\Formatter\LineFormatter
        format: "%datetime%-%channel%.%level_name% - %message%\n"
handlers:
    console:
        class: Monolog\Handler\StreamHandler
        level: DEBUG
        formatter: dashed
        processors: [memory_processor]
        stream: php://input
    info_file_handler:
        class: Monolog\Handler\StreamHandler
        level: INFO
        formatter: dashed
        stream: ./ofashion_info.log
    error_file_handler:
        class: Monolog\Handler\StreamHandler
        level: ERROR
        formatter: dashed
        stream: ./ofashion_error.log
processors:
    web_processor:
        class: Monolog\Processor\WebProcessor
    memory_processor:
        class: Monolog\Processor\MemoryUsageProcessor
loggers:
    ofashionLogger:
        handlers: [console, info_file_handler, error_file_handler]
        processors: [web_processor]